version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: strapi-postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi123
      POSTGRES_DB: strapidb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - strapi-net

  strapi:
    build: .
    container_name: strapi-app
    environment:
      NODE_ENV: production

      # Database
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapidb
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi123

      # REQUIRED STRAPI SECRETS
      APP_KEYS: key1,key2,key3,key4
      API_TOKEN_SALT: replace_with_random
      ADMIN_JWT_SECRET: replace_with_random
      JWT_SECRET: replace_with_random

    depends_on:
      - postgres
    ports:
      - "1337:1337"
    networks:
      - strapi-net

  nginx:
    image: nginx:latest
    container_name: strapi-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - strapi
    networks:
      - strapi-net

networks:
  strapi-net:
    driver: bridge

volumes:
  postgres-data:

